spring:
  application:
    name: bookhub

  datasource:
    url: jdbc:postgresql://localhost:5432/bookhub
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

google:
  books:
    api-key: ${GOOGLE_BOOKS_API_KEY:}
    base-url: https://www.googleapis.com/books/v1

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:}
  expiration: 86400000